# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('description', models.TextField(null=True)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='headshots')),
                ('visible', models.BooleanField(default=False)),
                ('github_url', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('personal_website', models.CharField(blank=True, max_length=200, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='bg-images')),
                ('team_type', models.CharField(choices=[('Core Team', 'Core Team'), ('Contributor', 'Contributor')], max_length=50)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
