# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('2600', '2600'), ('GEN', 'GEN'), ('PS', 'PS'), ('PS2', 'PS2'), ('PS3', 'PS3'), ('PS4', 'PS4'), ('PSV', 'PSV'), ('PSP', 'PSP'), ('XB', 'XB'), ('X360', 'X360'), ('XOne', 'XOne'), ('NES', 'NES'), ('SNES', 'SNES'), ('GC', 'GC'), ('GB', 'GB'), ('GBA', 'GBA'), ('N64', 'N64'), ('DS', 'DS'), ('3DS', '3DS'), ('Wii', 'Wii'), ('WiiU', 'WiiU'), ('NS', 'NS'), ('PC', 'PC'), ('Unknown', 'Unknown')], max_length=30)),
                ('release_date', models.DateField(verbose_name='release date')),
                ('release_year', models.DateField(verbose_name='release year')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Platform', 'Platform'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-playing', 'Role-playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Misc', 'Misc'), ('Unknown', 'Unknown')], max_length=30)),
                ('publisher', models.CharField(max_length=120)),
                ('developer', models.CharField(max_length=120)),
                ('rating', models.CharField(choices=[('RP', 'RP'), ('EC', 'EC'), ('E', 'E'), ('E10+', 'E10+'), ('T', 'T'), ('M', 'M'), ('AO', 'AO'), ('K-A', 'K-A'), ('Unknown', 'Unknown')], max_length=30)),
                ('na_sales', models.DecimalField(decimal_places=2, max_digits=3)),
                ('eu_sales', models.DecimalField(decimal_places=2, max_digits=3)),
                ('jp_sales', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ot_sales', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gb_sales', models.DecimalField(decimal_places=2, max_digits=3)),
                ('critic_score', models.IntegerField()),
                ('critic_count', models.IntegerField()),
                ('user_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user_count', models.IntegerField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title', 'platform'], name='games_title_cc9fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title', 'platform', 'rating'], name='games_title_0e6888_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['platform', 'genre'], name='games_platfor_c814a3_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['platform'], name='games_platfor_9a5cef_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['genre'], name='games_genre_ac3a20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('title', 'platform', 'developer')]),
        ),
    ]
