# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Platform', 'Platform'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-playing', 'Role-playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Misc', 'Misc')], max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('2600', 'Atari 2600'), ('GEN', 'Sega Genesis'), ('PS', 'Playstation'), ('PS2', 'Playstation 2'), ('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('PSV', 'Playstation Vita'), ('PSP', 'Playstation Portable'), ('XB', 'Xbox'), ('X360', 'Xbox 360'), ('XOne', 'Xbox One'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo Entertainment System'), ('GC', 'Game Boy Color'), ('GB', 'Game Boy'), ('GBA', 'Game Boy Advance'), ('N64', 'Nintendo 64'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo DS3'), ('Wii', 'Wii'), ('WiiU', 'WiiU'), ('NS', 'Nintendo Switch'), ('PC', 'PC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(choices=[('RP', 'Rating Pending'), ('EC', 'Early Childhood'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature'), ('AO', 'Adults Only'), ('K-A', 'Kids to Adults')], max_length=30),
        ),
    ]
