# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20171110_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('WANT TO PLAY', 'Want to Play'), ('HAVE PLAYED', 'Have Played'), ('NEVER', 'Never want to play'), ('OTHER', 'Other')], max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'list_of_games',
            },
        ),
        migrations.AddIndex(
            model_name='listofgames',
            index=models.Index(fields=['name', 'type'], name='list_of_gam_name_fba99b_idx'),
        ),
        migrations.AddIndex(
            model_name='listofgames',
            index=models.Index(fields=['name', 'type', 'game'], name='list_of_gam_name_536cdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listofgames',
            unique_together=set([('name', 'user', 'game')]),
        ),
    ]
