# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20171110_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfGames',
            new_name='GameList',
        ),
        migrations.RemoveIndex(
            model_name='gamelist',
            name='list_of_gam_name_fba99b_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamelist',
            name='list_of_gam_name_536cdd_idx',
        ),
        migrations.AddIndex(
            model_name='gamelist',
            index=models.Index(fields=['name', 'type'], name='game_list_name_5b3d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='gamelist',
            index=models.Index(fields=['name', 'type', 'game'], name='game_list_name_dd9115_idx'),
        ),
        migrations.AlterModelTable(
            name='gamelist',
            table='game_list',
        ),
    ]
