# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20171110_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_sequel',
            field=models.BooleanField(default=False),
        ),
    ]
