# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_is_sequel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('reviewer', models.CharField(max_length=120)),
                ('is_critic', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['game', 'is_critic'], name='comments_game_id_a81b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['game', 'is_user'], name='comments_game_id_ca5743_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('game', 'description')]),
        ),
    ]
