# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20171128_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_year',
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Platform', 'Platform'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-Playing', 'Role-Playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Misc', 'Misc'), ('Unknown', 'Unknown')], default='Unknown', max_length=30),
        ),
    ]
