# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20171128_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
