# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20171110_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='critic_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='critic_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='eu_sales',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gb_sales',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='jp_sales',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='na_sales',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ot_sales',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(null=True, verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.DateField(null=True, verbose_name='release year'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
