# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20171114_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='critic_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='critic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='eu_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gb_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fighting', 'Fighting'), ('Platform', 'Platform'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-playing', 'Role-playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Misc', 'Misc'), ('Unknown', 'Unknown')], default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='jp_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='na_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ot_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('2600', 'Atari 2600'), ('GEN', 'Sega Genesis'), ('PS', 'Playstation'), ('PS2', 'Playstation 2'), ('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('PSV', 'Playstation Vita'), ('PSP', 'Playstation Portable'), ('XB', 'Xbox'), ('X360', 'Xbox 360'), ('XOne', 'Xbox One'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo Entertainment System'), ('GC', 'Game Boy Color'), ('GB', 'Game Boy'), ('GBA', 'Game Boy Advance'), ('N64', 'Nintendo 64'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo DS3'), ('Wii', 'Wii'), ('WiiU', 'WiiU'), ('NS', 'Nintendo Switch'), ('PC', 'PC'), ('Unknown', 'Unknown')], default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(choices=[('RP', 'Rating Pending'), ('EC', 'Early Childhood'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature'), ('AO', 'Adults Only'), ('K-A', 'Kids to Adults'), ('Unknown', 'Unknown')], default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
