# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20171129_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment_magnitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
