# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0010_auto_20171209_0141'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gamelist',
            name='game_list_name_5b3d0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamelist',
            name='game_list_name_dd9115_idx',
        ),
        migrations.AlterUniqueTogether(
            name='gamelist',
            unique_together=set([('user', 'game', 'type')]),
        ),
        migrations.AddIndex(
            model_name='gamelist',
            index=models.Index(fields=['type', 'game'], name='game_list_type_ed280d_idx'),
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='name',
        ),
    ]
