# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0011_auto_20171210_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='type',
            field=models.CharField(choices=[('WANT TO PLAY', 'Want to Play'), ('HAVE PLAYED', 'Have Played'), ('NEVER', 'Never want to play')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='gamelist',
            unique_together=set([('user', 'game')]),
        ),
    ]
