# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20171210_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='type',
            field=models.CharField(choices=[('WANT TO PLAY', 'Want to Play'), ('HAVE PLAYED', 'Have Played'), ('NEVER', 'Never want to play'), ('CURRENTLY PLAYING', 'Currently Playing')], max_length=30),
        ),
    ]
