# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20171210_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
