# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
