# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20171210_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img_url',
            field=models.CharField(default='', max_length=120),
        ),
    ]
