# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20171211_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='game',
            name='img_url',
            field=models.CharField(default='', max_length=120),
        ),
    ]
